# Generated by Django 5.1.6 on 2025-02-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('references_legales', models.TextField(help_text='Textes de loi, arrêtés et dates mentionnés dans le document.', verbose_name='Références légales')),
                ('denomination_commerciale', models.CharField(max_length=255, verbose_name='Dénomination commerciale')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('classification', models.CharField(max_length=255, verbose_name='Classification')),
                ('caracteristiques', models.TextField(verbose_name='Caractéristiques')),
                ('conditions_conservation', models.TextField(verbose_name='Conditions de conservation')),
                ('duree_stabilite', models.CharField(max_length=100, verbose_name='Durée de stabilité')),
                ('est_valide', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
