# Generated by Django 5.1.6 on 2025-02-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteur_app', '0002_remove_certificat_references_legales'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='adress',
            field=models.CharField(default='', max_length=300, verbose_name='Adresse du demendeur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificat',
            name='adress_produit',
            field=models.CharField(default='', max_length=300, verbose_name='Adresse du production'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificat',
            name='nom_produit',
            field=models.CharField(default='', max_length=400, verbose_name='Nom du produit'),
            preserve_default=False,
        ),
    ]
