# Generated by Django 5.1.6 on 2025-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteur_app', '0003_certificat_adress_certificat_adress_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificat',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='certificat',
            name='adress',
            field=models.CharField(max_length=300, verbose_name="adresse de l'établissement de détenteur/titulaire de l'autorisation de commerciale provisoire (ACP)"),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='adress_produit',
            field=models.CharField(max_length=300, verbose_name="Adresse de l'établissemnt exploitant de ACP"),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='nom',
            field=models.CharField(max_length=100, verbose_name="nom de l'établissement de détenteur/titulaire de l'autorisation de commerciale provisoire (ACP)"),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='nom_produit',
            field=models.CharField(max_length=400, verbose_name="Nom de l'établissemnt exploitant de ACP"),
        ),
    ]
