# Generated by Django 5.1.6 on 2025-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteur_app', '0004_remove_certificat_prenom_alter_certificat_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='adress_fabric',
            field=models.CharField(default='', max_length=400, verbose_name="Adresse de l'établissement fabriquant du dispositif médical"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificat',
            name='nom_fabric',
            field=models.CharField(default='', max_length=400, verbose_name="Nom de l'établissement fabriquant du dispositif médical"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificat',
            name='nom_pharma',
            field=models.CharField(default='', max_length=200, verbose_name='Nom et prénom du pharmacien directeur technique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificat',
            name='organisme',
            field=models.TextField(default='', verbose_name='Organismes Certificateurs ou Organismes Equivalentes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificat',
            name='adress',
            field=models.CharField(max_length=400, verbose_name="adresse de l'établissement de détenteur/titulaire de l'autorisation de commerciale provisoire (ACP)"),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='adress_produit',
            field=models.CharField(max_length=400, verbose_name="Adresse de l'établissemnt exploitant de ACP"),
        ),
    ]
