# Generated by Django 5.1.6 on 2025-02-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteur_app', '0005_certificat_adress_fabric_certificat_nom_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificats_pdf/', verbose_name='Fichier PDF Joint'),
        ),
    ]
