# Generated by Django 5.1.6 on 2025-02-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteur_app', '0006_certificat_fichier_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificat',
            options={'ordering': ['-date_creation', 'denomination_commerciale'], 'verbose_name': 'Certificat', 'verbose_name_plural': 'Certificats'},
        ),
        migrations.AlterField(
            model_name='certificat',
            name='adress',
            field=models.CharField(max_length=400, verbose_name="Adresse de l'établissement de détenteur/titulaire de l'autorisation de commerciale provisoire (ACP)"),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='denomination_commerciale',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Dénomination commerciale'),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='designation',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='est_valide',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est Valide'),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='nom',
            field=models.CharField(max_length=100, verbose_name="Nom de l'établissement de détenteur/titulaire de l'autorisation de commerciale provisoire (ACP)"),
        ),
        migrations.AddIndex(
            model_name='certificat',
            index=models.Index(fields=['denomination_commerciale', 'designation'], name='cert_name_desig_idx'),
        ),
    ]
